const mongoose = require("mongoose");
const sanitizeHtml = require("sanitize-html");
const Blog = require("../models/Blog");

/* =========================
   SANITIZE CONFIG
========================= */
const sanitizeConfig = {
  allowedTags: [
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "p",
    "br",
    "hr",
    "ul",
    "ol",
    "li",
    "strong",
    "b",
    "em",
    "i",
    "u",
    "blockquote",
    "pre",
    "code",
    "img",
    "a",
    "span",
    "div",
  ],
  allowedAttributes: {
    a: ["href", "target", "rel"],
    img: ["src", "alt", "width", "height"],
    span: ["style"],
    div: ["style"],
    p: ["style"],
    h1: ["style"],
    h2: ["style"],
    h3: ["style"],
  },
  allowedStyles: {
    "*": {
      "text-align": [/^left|right|center|justify$/],
      color: [/^#[0-9a-fA-F]+$/],
      "font-weight": [/^\d+$/],
    },
  },
};

/* =========================
   IMAGE URL HELPERS
========================= */
function isDirectImageUrl(url) {
  return /\.(jpg|jpeg|png|webp|gif|svg)$/i.test(url);
}

function isGoogleBlocked(url) {
  return /drive\.google\.com|photos\.google\.com/i.test(url);
}

function normalizeDropboxUrl(url) {
  if (url.includes("dropbox.com")) {
    return url
      .replace("www.dropbox.com", "dl.dropboxusercontent.com")
      .replace("?dl=0", "");
  }
  return null;
}

/* =========================
   GET ALL BLOGS (PAGINATED)
========================= */
exports.getAllBlogs = async (req, res, next) => {
  try {
    const page = Math.max(Number(req.query.page) || 1, 1);
    const limit = Math.min(Number(req.query.limit) || 6, 20);
    const skip = (page - 1) * limit;

    const [blogs, total] = await Promise.all([
      Blog.find().sort({ createdAt: -1 }).skip(skip).limit(limit),
      Blog.countDocuments(),
    ]);

    res.json({ blogs, total, page, limit });
  } catch (err) {
    next(err);
  }
};

/* =========================
   GET BLOG BY ID
========================= */
exports.getBlogById = async (req, res, next) => {
  try {
    if (!mongoose.Types.ObjectId.isValid(req.params.id)) {
      return res.status(400).json({ message: "Invalid blog ID" });
    }

    const blog = await Blog.findById(req.params.id);
    if (!blog) {
      return res.status(404).json({ message: "Blog not found" });
    }

    res.json(blog);
  } catch (err) {
    next(err);
  }
};

exports.getBlogBySlug = async (req, res, next) => {
  try {
    const blog = await Blog.findOne({ slug: req.params.slug });
    if (!blog) {
      return res.status(404).json({ message: "Blog not found" });
    }
    res.json(blog);
  } catch (err) {
    next(err);
  }
};

/* =========================
   CREATE BLOG (FIXED WITH LOGGING)
========================= */
exports.createBlog = async (req, res, next) => {
  try {
    console.log("📥 CREATE BLOG REQUEST");
    console.log("req.file:", req.file);
    console.log("req.body.imageUrl:", req.body.imageUrl);
    console.log("req.body.videoUrl:", req.body.videoUrl);

    const {
      title,
      type,
      category,
      excerpt,
      content,
      author,
      imageUrl,
      videoUrl,
      courseData,
    } = req.body;

    const blogData = {
      title,
      type,
      category,
      excerpt,
      author,
      content: sanitizeHtml(content || "", sanitizeConfig),
      slug: undefined, // auto-generated by schema
      metaTitle: req.body.metaTitle,
      metaDescription: req.body.metaDescription,
    };

    if (courseData) {
      try {
        blogData.courseData = JSON.parse(courseData);
      } catch {
        return res.status(400).json({ message: "Invalid course data" });
      }
    }

    // CRITICAL: Process image first
    let imageProcessed = false;

    // Priority 1: Uploaded file
    if (req.file) {
      blogData.image = `/uploads/${req.file.filename}`;
      imageProcessed = true;
      console.log("✅ Image from file:", blogData.image);
    }
    // Priority 2: Image URL
    else if (imageUrl && imageUrl.trim()) {
      const trimmedUrl = imageUrl.trim();

      if (isGoogleBlocked(trimmedUrl)) {
        return res.status(400).json({
          message: "Google Drive / Photos links are not supported",
        });
      }

      const dropboxUrl = normalizeDropboxUrl(trimmedUrl);
      if (dropboxUrl) {
        blogData.image = dropboxUrl;
        imageProcessed = true;
        console.log("✅ Image from Dropbox URL:", blogData.image);
      } else if (isDirectImageUrl(trimmedUrl)) {
        blogData.image = trimmedUrl;
        imageProcessed = true;
        console.log("✅ Image from direct URL:", blogData.image);
      } else {
        return res.status(400).json({
          message: "Invalid image URL format",
        });
      }
    }

    // Validate image was provided
    if (!imageProcessed) {
      console.log("❌ No image provided");
      return res.status(400).json({
        message: "Image is required for all blogs",
      });
    }

    // Optional: Add video URL
    if (videoUrl && videoUrl.trim()) {
      blogData.videoUrl = videoUrl.trim();
      console.log("✅ Video URL:", blogData.videoUrl);
    }

    console.log("💾 Creating blog with data:", {
      ...blogData,
      content: "[content hidden]",
    });

    const blog = await Blog.create(blogData);

    console.log("✅ Blog created successfully:", {
      _id: blog._id,
      image: blog.image,
      videoUrl: blog.videoUrl,
    });

    res.status(201).json(blog);
  } catch (err) {
    console.error("❌ CREATE BLOG ERROR:", err);
    next(err);
  }
};

/* =========================
   UPDATE BLOG (FIXED WITH LOGGING)
========================= */
exports.updateBlog = async (req, res, next) => {
  try {
    console.log("📥 UPDATE BLOG REQUEST");
    console.log("req.file:", req.file);
    console.log("req.body.imageUrl:", req.body.imageUrl);
    console.log("req.body.videoUrl:", req.body.videoUrl);

    if (!mongoose.Types.ObjectId.isValid(req.params.id)) {
      return res.status(400).json({ message: "Invalid blog ID" });
    }

    const {
      title,
      type,
      category,
      excerpt,
      content,
      author,
      imageUrl,
      videoUrl,
      courseData,
    } = req.body;

    const updateData = {
      title,
      type,
      category,
      excerpt,
      author,
    };

    if (req.body.metaTitle !== undefined) {
      updateData.metaTitle = req.body.metaTitle;
    }

    if (req.body.metaDescription !== undefined) {
      updateData.metaDescription = req.body.metaDescription;
    }

    if (content) {
      updateData.content = sanitizeHtml(content, sanitizeConfig);
    }

    if (courseData) {
      try {
        updateData.courseData = JSON.parse(courseData);
      } catch {
        return res.status(400).json({ message: "Invalid course data" });
      }
    }

    // Process image if provided
    if (req.file) {
      updateData.image = `/uploads/${req.file.filename}`;
      console.log("✅ Updated image from file:", updateData.image);
    } else if (imageUrl && imageUrl.trim()) {
      const trimmedUrl = imageUrl.trim();

      if (isGoogleBlocked(trimmedUrl)) {
        return res.status(400).json({
          message: "Google Drive / Photos links are not supported",
        });
      }

      const dropboxUrl = normalizeDropboxUrl(trimmedUrl);
      if (dropboxUrl) {
        updateData.image = dropboxUrl;
        console.log("✅ Updated image from Dropbox URL:", updateData.image);
      } else if (isDirectImageUrl(trimmedUrl)) {
        updateData.image = trimmedUrl;
        console.log("✅ Updated image from direct URL:", updateData.image);
      } else {
        return res.status(400).json({ message: "Invalid image URL" });
      }
    }

    // Update video if provided (can be removed by sending empty string)
    if (videoUrl !== undefined) {
      updateData.videoUrl = videoUrl.trim() || undefined;
      console.log("✅ Updated video URL:", updateData.videoUrl);
    }

    const existing = await Blog.findById(req.params.id);
    if (!existing) {
      return res.status(404).json({ message: "Blog not found" });
    }

    // Validate that blog will have either video or image after update
    const willHaveVideo =
      updateData.videoUrl !== undefined
        ? !!updateData.videoUrl
        : !!existing.videoUrl;
    const willHaveImage =
      updateData.image !== undefined ? !!updateData.image : !!existing.image;

    if (!willHaveVideo && !willHaveImage) {
      return res.status(400).json({
        message: "Blog must have either a video or an image",
      });
    }

    console.log("💾 Updating blog with data:", {
      ...updateData,
      content: updateData.content ? "[content hidden]" : undefined,
    });

    const updated = await Blog.findByIdAndUpdate(req.params.id, updateData, {
      new: true,
    });

    console.log("✅ Blog updated successfully:", {
      _id: updated._id,
      image: updated.image,
      videoUrl: updated.videoUrl,
    });

    res.json(updated);
  } catch (err) {
    console.error("❌ UPDATE BLOG ERROR:", err);
    next(err);
  }
};

/* =========================
   DELETE BLOG
========================= */
exports.deleteBlog = async (req, res, next) => {
  try {
    if (!mongoose.Types.ObjectId.isValid(req.params.id)) {
      return res.status(400).json({ message: "Invalid blog ID" });
    }

    const blog = await Blog.findByIdAndDelete(req.params.id);
    if (!blog) {
      return res.status(404).json({ message: "Blog not found" });
    }

    res.json({ message: "Blog deleted successfully" });
  } catch (err) {
    next(err);
  }
};
